In [128]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [129]:
# Data Loading
data = r'C:\Users\uzair\Downloads\Spotify\dataset.csv'
pd.set_option("display.max_columns", None)
df = pd.read_csv(data)
df.head() #114000 rows × 21 columns

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [130]:
# data exploration
print('Shape:' , df.shape)
print('Columns: ', df.columns)
print('Duplicated Track: ',df.duplicated(subset=['track_id']).sum())
print('x-----------------------------------------------------------------------------------------------x')
df.info()
df.describe()

Shape: (114000, 21)
Columns:  Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='object')
Duplicated Track:  24259
x-----------------------------------------------------------------------------------------------x
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  object
 2   artists           113999 non-null  object
 3   album_name        113999 non-null  object
 4   track_name        113999 non-null  object
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(6), object(5)
memory usage: 17.5+ MB

,Unnamed: 0,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000000,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,56999.500000,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,32909.109681,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28499.750000,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,56999.500000,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,85499.250000,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,113999.000000,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [131]:
df.isnull().sum()

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [132]:
# Data Cleaning
df = df.drop(columns=['Unnamed: 0'], errors='ignore')
df = df.drop_duplicates(subset=['track_id'])
df = df.dropna(subset=['popularity','danceability','energy','valence'])
dfClean = df.copy()

In [133]:
hitThreshold = dfClean['popularity'].quantile(0.80)
dfClean['isHit'] = dfClean['popularity'] >= hitThreshold
dfClean[['track_name','artists','popularity','isHit']].head()

                   track_name                 artists  popularity  isHit
0                      Comedy             Gen Hoshino          73   True
1            Ghost - Acoustic            Ben Woodward          55   True
2              To Begin Again  Ingrid Michaelson;ZAYN          57   True
3  Can't Help Falling In Love            Kina Grannis          71   True
4                     Hold On        Chord Overstreet          82   True

In [134]:
audioFeatures = [
    'danceability',
    'energy',
    'valence',
    'acousticness',
    'instrumentalness',
    'liveness',
    'speechiness'
]
hitDNA = dfClean.groupby('isHit')[audioFeatures].mean()

hitDNA

,danceability,energy,valence,acousticness,instrumentalness,liveness,speechiness
isHit,,,,,,,
False,0.556793,0.637224,0.472331,0.334877,0.189226,0.225623,0.090019
True,0.582484,0.623996,0.458687,0.303377,0.113617,0.184247,0.077698

In [135]:
featureCorr = dfClean[audioFeatures + ['popularity']].corr()

featureCorr['popularity'].sort_values(ascending=False)

popularity          1.000000
danceability        0.064281
energy              0.013728
valence            -0.011526
liveness           -0.013844
acousticness       -0.038847
speechiness        -0.047081
instrumentalness   -0.127465
Name: popularity, dtype: float64

In [136]:
artistStats = dfClean.groupby('artists').agg(
    trackCount=('track_id','count'),
    avgPopularity=('popularity','mean'),
    avgDanceability=('danceability','mean'),
    avgEnergy=('energy','mean'),
    avgValence=('valence','mean')
).reset_index()

artistStats.head()

,artists,trackCount,avgPopularity,avgDanceability,avgEnergy,avgValence
0,!nvite,2,23.000000,0.8205,0.519,0.415
1,"""Puppy Dog Pals"" Cast",2,57.500000,0.7050,0.856,0.915
2,"""Weird Al"" Yankovic",15,26.333333,0.6574,0.575,0.736
3,#Kids;Nursery Rhymes;Nursery Rhymes and Kids S...,1,34.000000,0.5800,0.494,0.908
4,$affie,1,39.000000,0.7440,0.178,0.230

In [138]:
artistHitRate = dfClean.groupby('artists')['isHit'].mean().reset_index()

artistHitRate.rename(columns={'isHit':'hitRate'}, inplace=True)

artistStats = artistStats.merge(artistHitRate, on='artists')

In [139]:
artistStats

,artists,trackCount,avgPopularity,avgDanceability,avgEnergy,avgValence,hitRate
0,!nvite,2,23.000000,0.8205,0.519000,0.4150,0.000000
1,"""Puppy Dog Pals"" Cast",2,57.500000,0.7050,0.856000,0.9150,1.000000
2,"""Weird Al"" Yankovic",15,26.333333,0.6574,0.575000,0.7360,0.066667
3,#Kids;Nursery Rhymes;Nursery Rhymes and Kids S...,1,34.000000,0.5800,0.494000,0.9080,0.000000
4,$affie,1,39.000000,0.7440,0.178000,0.2300,0.000000
...,...,...,...,...,...,...,...
31432,黃仲崑,3,24.333333,0.5640,0.533333,0.3180,0.000000
31433,黃妃,2,24.000000,0.5500,0.649500,0.4865,0.000000
31434,黃小琥,1,56.000000,0.3340,0.431000,0.2120,1.000000
31435,黃敏華,1,20.000000,0.5490,0.478000,0.3410,0.000000
31436,龍藏Ryuzo,2,21.500000,0.4975,0.416500,0.3920,0.000000

In [140]:
emergingArtists = artistStats[
    (artistStats['trackCount'] >= 3) &
    (artistStats['trackCount'] <= 10)
]

emergingArtists = emergingArtists.sort_values(
    by=['avgPopularity','hitRate'],
    ascending=False
)

emergingArtists.head(20)

,artists,trackCount,avgPopularity,avgDanceability,avgEnergy,avgValence,hitRate
11491,Harry Styles,3,92.000000,0.529333,0.759333,0.627000,1.0
20474,Olivia Rodrigo,5,87.400000,0.468200,0.497800,0.285180,1.0
12150,IVE,3,84.000000,0.737000,0.787333,0.641333,1.0
19088,Morgan Wallen,3,83.333333,0.616667,0.729000,0.534333,1.0
15927,Lil Nas X,5,83.200000,0.696800,0.620400,0.565800,1.0
20535,One Direction,5,83.000000,0.652800,0.688200,0.536800,1.0
19314,Måneskin,5,82.600000,0.648800,0.763600,0.645400,1.0
26532,TV Girl,3,81.666667,0.618000,0.811667,0.576333,1.0
8697,Eminem,6,81.166667,0.809333,0.775167,0.540267,1.0
2124,Ariana Grande,9,80.777778,0.704444,0.623222,0.371000,1.0
16710,Luke Combs,3,80.333333,0.548667,0.599000,0.434000,1.0
22661,Rauw Alejandro,3,79.666667,0.775000,0.687333,0.313333,1.0
28517,Troye Sivan,3,78.666667,0.588333,0.611000,0.393333,1.0
18882,Mitski,6,78.333333,0.481000,0.610167,0.443000,1.0
3150,Beach Bunny,3,78.000000,0.465333,0.867667,0.725667,1.0
15257,LE SSERAFIM,4,78.000000,0.826250,0.735750,0.685250,1.0
22842,Rels B,5,78.000000,0.737200,0.507400,0.364400,1.0
5039,Charlie Puth;Jung Kook;BTS,3,77.666667,0.881000,0.592000,0.719000,1.0
17022,MGMT,4,77.500000,0.589250,0.846500,0.443500,1.0
19112,Mother Mother,3,77.333333,0.456333,0.847667,0.275667,1.0

In [141]:
genreStats = dfClean.groupby('track_genre').agg(
    avgPopularity=('popularity','mean'),
    volume=('track_id','count')
).reset_index()

genreStats.head()

   track_genre  avgPopularity  volume
0     acoustic      42.483000    1000
1     afrobeat      24.407407     999
2     alt-rock      33.896897     999
3  alternative      22.218673     407
4      ambient      44.208208     999

In [142]:
totalTracks = genreStats['volume'].sum()

genreStats['marketShare'] = genreStats['volume'] / totalTracks

genreStats.sort_values('avgPopularity', ascending=False).head(10)

   track_genre  avgPopularity  volume  marketShare
65       k-pop      59.358779     917     0.010218
81    pop-film      59.096933     815     0.009082
71       metal      56.422414     232     0.002585
15       chill      53.738683     972     0.010831
68      latino      51.788945     398     0.004435
94         sad      51.109929     564     0.006285
44      grunge      50.587007     862     0.009605
55      indian      49.765348     733     0.008168
5        anime      48.776884     995     0.011087
33         emo      48.500000     932     0.010385

In [143]:
genreHitRate = dfClean.groupby('track_genre')['isHit'].mean().reset_index()

genreHitRate.rename(columns={'isHit':'hitRate'}, inplace=True)

genreHitRate.sort_values('hitRate', ascending=False).head(10)

   track_genre   hitRate
81    pop-film  0.942331
15       chill  0.729424
71       metal  0.702586
65       k-pop  0.690294
51     hip-hop  0.648456
44      grunge  0.599768
80         pop  0.572115
30         edm  0.547550
94         sad  0.546099
11     british  0.535556

In [144]:
marketOpportunity = genreStats.sort_values(
    ['avgPopularity','volume'],
    ascending=[False,True]
)

marketOpportunity.head(10)

   track_genre  avgPopularity  volume  marketShare
65       k-pop      59.358779     917     0.010218
81    pop-film      59.096933     815     0.009082
71       metal      56.422414     232     0.002585
15       chill      53.738683     972     0.010831
68      latino      51.788945     398     0.004435
94         sad      51.109929     564     0.006285
44      grunge      50.587007     862     0.009605
55      indian      49.765348     733     0.008168
5        anime      48.776884     995     0.011087
33         emo      48.500000     932     0.010385

In [147]:
correlation = artistStats['trackCount'].corr(artistStats['avgPopularity'])

print("Correlation between productivity and popularity:", correlation)

Correlation between productivity and popularity: -0.08109236342362469

In [148]:
topEmergingArtists = emergingArtists[
    ['artists','trackCount','avgPopularity','hitRate']
].head(20)

topEmergingArtists

                          artists  trackCount  avgPopularity  hitRate
11491                Harry Styles           3      92.000000      1.0
20474              Olivia Rodrigo           5      87.400000      1.0
12150                         IVE           3      84.000000      1.0
19088               Morgan Wallen           3      83.333333      1.0
15927                   Lil Nas X           5      83.200000      1.0
20535               One Direction           5      83.000000      1.0
19314                    Måneskin           5      82.600000      1.0
26532                     TV Girl           3      81.666667      1.0
8697                       Eminem           6      81.166667      1.0
2124                Ariana Grande           9      80.777778      1.0
16710                  Luke Combs           3      80.333333      1.0
22661              Rauw Alejandro           3      79.666667      1.0
28517                 Troye Sivan           3      78.666667      1.0
18882                      Mitski           6      78.333333      1.0
3150                  Beach Bunny           3      78.000000      1.0
15257                 LE SSERAFIM           4      78.000000      1.0
22842                      Rels B           5      78.000000      1.0
5039   Charlie Puth;Jung Kook;BTS           3      77.666667      1.0
17022                        MGMT           4      77.500000      1.0
19112               Mother Mother           3      77.333333      1.0